// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/TaroPood/taropood/internal/repository/postgres/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newActionModel(db *gorm.DB, opts ...gen.DOOption) actionModel {
	_actionModel := actionModel{}

	_actionModel.actionModelDo.UseDB(db, opts...)
	_actionModel.actionModelDo.UseModel(&model.ActionModel{})

	tableName := _actionModel.actionModelDo.TableName()
	_actionModel.ALL = field.NewAsterisk(tableName)
	_actionModel.ID = field.NewString(tableName, "id")
	_actionModel.RuleID = field.NewString(tableName, "rule_id")
	_actionModel.Type = field.NewString(tableName, "type")
	_actionModel.Config = field.NewBytes(tableName, "config")
	_actionModel.Order = field.NewInt(tableName, "order")
	_actionModel.CreatedAt = field.NewTime(tableName, "created_at")

	_actionModel.fillFieldMap()

	return _actionModel
}

type actionModel struct {
	actionModelDo actionModelDo

	ALL       field.Asterisk
	ID        field.String
	RuleID    field.String
	Type      field.String
	Config    field.Bytes
	Order     field.Int
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (a actionModel) Table(newTableName string) *actionModel {
	a.actionModelDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a actionModel) As(alias string) *actionModel {
	a.actionModelDo.DO = *(a.actionModelDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *actionModel) updateTableName(table string) *actionModel {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.RuleID = field.NewString(table, "rule_id")
	a.Type = field.NewString(table, "type")
	a.Config = field.NewBytes(table, "config")
	a.Order = field.NewInt(table, "order")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *actionModel) WithContext(ctx context.Context) IActionModelDo {
	return a.actionModelDo.WithContext(ctx)
}

func (a actionModel) TableName() string { return a.actionModelDo.TableName() }

func (a actionModel) Alias() string { return a.actionModelDo.Alias() }

func (a actionModel) Columns(cols ...field.Expr) gen.Columns { return a.actionModelDo.Columns(cols...) }

func (a *actionModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *actionModel) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["rule_id"] = a.RuleID
	a.fieldMap["type"] = a.Type
	a.fieldMap["config"] = a.Config
	a.fieldMap["order"] = a.Order
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a actionModel) clone(db *gorm.DB) actionModel {
	a.actionModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a actionModel) replaceDB(db *gorm.DB) actionModel {
	a.actionModelDo.ReplaceDB(db)
	return a
}

type actionModelDo struct{ gen.DO }

type IActionModelDo interface {
	gen.SubQuery
	Debug() IActionModelDo
	WithContext(ctx context.Context) IActionModelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IActionModelDo
	WriteDB() IActionModelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IActionModelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IActionModelDo
	Not(conds ...gen.Condition) IActionModelDo
	Or(conds ...gen.Condition) IActionModelDo
	Select(conds ...field.Expr) IActionModelDo
	Where(conds ...gen.Condition) IActionModelDo
	Order(conds ...field.Expr) IActionModelDo
	Distinct(cols ...field.Expr) IActionModelDo
	Omit(cols ...field.Expr) IActionModelDo
	Join(table schema.Tabler, on ...field.Expr) IActionModelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IActionModelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IActionModelDo
	Group(cols ...field.Expr) IActionModelDo
	Having(conds ...gen.Condition) IActionModelDo
	Limit(limit int) IActionModelDo
	Offset(offset int) IActionModelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IActionModelDo
	Unscoped() IActionModelDo
	Create(values ...*model.ActionModel) error
	CreateInBatches(values []*model.ActionModel, batchSize int) error
	Save(values ...*model.ActionModel) error
	First() (*model.ActionModel, error)
	Take() (*model.ActionModel, error)
	Last() (*model.ActionModel, error)
	Find() ([]*model.ActionModel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ActionModel, err error)
	FindInBatches(result *[]*model.ActionModel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ActionModel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IActionModelDo
	Assign(attrs ...field.AssignExpr) IActionModelDo
	Joins(fields ...field.RelationField) IActionModelDo
	Preload(fields ...field.RelationField) IActionModelDo
	FirstOrInit() (*model.ActionModel, error)
	FirstOrCreate() (*model.ActionModel, error)
	FindByPage(offset int, limit int) (result []*model.ActionModel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IActionModelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a actionModelDo) Debug() IActionModelDo {
	return a.withDO(a.DO.Debug())
}

func (a actionModelDo) WithContext(ctx context.Context) IActionModelDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a actionModelDo) ReadDB() IActionModelDo {
	return a.Clauses(dbresolver.Read)
}

func (a actionModelDo) WriteDB() IActionModelDo {
	return a.Clauses(dbresolver.Write)
}

func (a actionModelDo) Session(config *gorm.Session) IActionModelDo {
	return a.withDO(a.DO.Session(config))
}

func (a actionModelDo) Clauses(conds ...clause.Expression) IActionModelDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a actionModelDo) Returning(value interface{}, columns ...string) IActionModelDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a actionModelDo) Not(conds ...gen.Condition) IActionModelDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a actionModelDo) Or(conds ...gen.Condition) IActionModelDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a actionModelDo) Select(conds ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a actionModelDo) Where(conds ...gen.Condition) IActionModelDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a actionModelDo) Order(conds ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a actionModelDo) Distinct(cols ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a actionModelDo) Omit(cols ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a actionModelDo) Join(table schema.Tabler, on ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a actionModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a actionModelDo) RightJoin(table schema.Tabler, on ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a actionModelDo) Group(cols ...field.Expr) IActionModelDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a actionModelDo) Having(conds ...gen.Condition) IActionModelDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a actionModelDo) Limit(limit int) IActionModelDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a actionModelDo) Offset(offset int) IActionModelDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a actionModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IActionModelDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a actionModelDo) Unscoped() IActionModelDo {
	return a.withDO(a.DO.Unscoped())
}

func (a actionModelDo) Create(values ...*model.ActionModel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a actionModelDo) CreateInBatches(values []*model.ActionModel, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a actionModelDo) Save(values ...*model.ActionModel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a actionModelDo) First() (*model.ActionModel, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActionModel), nil
	}
}

func (a actionModelDo) Take() (*model.ActionModel, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActionModel), nil
	}
}

func (a actionModelDo) Last() (*model.ActionModel, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActionModel), nil
	}
}

func (a actionModelDo) Find() ([]*model.ActionModel, error) {
	result, err := a.DO.Find()
	return result.([]*model.ActionModel), err
}

func (a actionModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ActionModel, err error) {
	buf := make([]*model.ActionModel, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a actionModelDo) FindInBatches(result *[]*model.ActionModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a actionModelDo) Attrs(attrs ...field.AssignExpr) IActionModelDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a actionModelDo) Assign(attrs ...field.AssignExpr) IActionModelDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a actionModelDo) Joins(fields ...field.RelationField) IActionModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a actionModelDo) Preload(fields ...field.RelationField) IActionModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a actionModelDo) FirstOrInit() (*model.ActionModel, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActionModel), nil
	}
}

func (a actionModelDo) FirstOrCreate() (*model.ActionModel, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActionModel), nil
	}
}

func (a actionModelDo) FindByPage(offset int, limit int) (result []*model.ActionModel, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a actionModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a actionModelDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a actionModelDo) Delete(models ...*model.ActionModel) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *actionModelDo) withDO(do gen.Dao) *actionModelDo {
	a.DO = *do.(*gen.DO)
	return a
}
