// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/TaroPood/taropood/internal/repository/postgres/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newRuleModel(db *gorm.DB, opts ...gen.DOOption) ruleModel {
	_ruleModel := ruleModel{}

	_ruleModel.ruleModelDo.UseDB(db, opts...)
	_ruleModel.ruleModelDo.UseModel(&model.RuleModel{})

	tableName := _ruleModel.ruleModelDo.TableName()
	_ruleModel.ALL = field.NewAsterisk(tableName)
	_ruleModel.ID = field.NewString(tableName, "id")
	_ruleModel.Name = field.NewString(tableName, "name")
	_ruleModel.ConditionType = field.NewString(tableName, "condition_type")
	_ruleModel.ConditionConfig = field.NewBytes(tableName, "condition_config")
	_ruleModel.Priority = field.NewInt(tableName, "priority")
	_ruleModel.Enabled = field.NewBool(tableName, "enabled")
	_ruleModel.Tags = field.NewField(tableName, "tags")
	_ruleModel.Metadata = field.NewBytes(tableName, "metadata")
	_ruleModel.CreatedAt = field.NewTime(tableName, "created_at")
	_ruleModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_ruleModel.Actions = ruleModelHasManyActions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Actions", "model.ActionModel"),
	}

	_ruleModel.fillFieldMap()

	return _ruleModel
}

type ruleModel struct {
	ruleModelDo ruleModelDo

	ALL             field.Asterisk
	ID              field.String
	Name            field.String
	ConditionType   field.String
	ConditionConfig field.Bytes
	Priority        field.Int
	Enabled         field.Bool
	Tags            field.Field
	Metadata        field.Bytes
	CreatedAt       field.Time
	UpdatedAt       field.Time
	Actions         ruleModelHasManyActions

	fieldMap map[string]field.Expr
}

func (r ruleModel) Table(newTableName string) *ruleModel {
	r.ruleModelDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r ruleModel) As(alias string) *ruleModel {
	r.ruleModelDo.DO = *(r.ruleModelDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *ruleModel) updateTableName(table string) *ruleModel {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.Name = field.NewString(table, "name")
	r.ConditionType = field.NewString(table, "condition_type")
	r.ConditionConfig = field.NewBytes(table, "condition_config")
	r.Priority = field.NewInt(table, "priority")
	r.Enabled = field.NewBool(table, "enabled")
	r.Tags = field.NewField(table, "tags")
	r.Metadata = field.NewBytes(table, "metadata")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *ruleModel) WithContext(ctx context.Context) IRuleModelDo {
	return r.ruleModelDo.WithContext(ctx)
}

func (r ruleModel) TableName() string { return r.ruleModelDo.TableName() }

func (r ruleModel) Alias() string { return r.ruleModelDo.Alias() }

func (r ruleModel) Columns(cols ...field.Expr) gen.Columns { return r.ruleModelDo.Columns(cols...) }

func (r *ruleModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *ruleModel) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["name"] = r.Name
	r.fieldMap["condition_type"] = r.ConditionType
	r.fieldMap["condition_config"] = r.ConditionConfig
	r.fieldMap["priority"] = r.Priority
	r.fieldMap["enabled"] = r.Enabled
	r.fieldMap["tags"] = r.Tags
	r.fieldMap["metadata"] = r.Metadata
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt

}

func (r ruleModel) clone(db *gorm.DB) ruleModel {
	r.ruleModelDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Actions.db = db.Session(&gorm.Session{Initialized: true})
	r.Actions.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r ruleModel) replaceDB(db *gorm.DB) ruleModel {
	r.ruleModelDo.ReplaceDB(db)
	r.Actions.db = db.Session(&gorm.Session{})
	return r
}

type ruleModelHasManyActions struct {
	db *gorm.DB

	field.RelationField
}

func (a ruleModelHasManyActions) Where(conds ...field.Expr) *ruleModelHasManyActions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a ruleModelHasManyActions) WithContext(ctx context.Context) *ruleModelHasManyActions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a ruleModelHasManyActions) Session(session *gorm.Session) *ruleModelHasManyActions {
	a.db = a.db.Session(session)
	return &a
}

func (a ruleModelHasManyActions) Model(m *model.RuleModel) *ruleModelHasManyActionsTx {
	return &ruleModelHasManyActionsTx{a.db.Model(m).Association(a.Name())}
}

func (a ruleModelHasManyActions) Unscoped() *ruleModelHasManyActions {
	a.db = a.db.Unscoped()
	return &a
}

type ruleModelHasManyActionsTx struct{ tx *gorm.Association }

func (a ruleModelHasManyActionsTx) Find() (result []*model.ActionModel, err error) {
	return result, a.tx.Find(&result)
}

func (a ruleModelHasManyActionsTx) Append(values ...*model.ActionModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a ruleModelHasManyActionsTx) Replace(values ...*model.ActionModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a ruleModelHasManyActionsTx) Delete(values ...*model.ActionModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a ruleModelHasManyActionsTx) Clear() error {
	return a.tx.Clear()
}

func (a ruleModelHasManyActionsTx) Count() int64 {
	return a.tx.Count()
}

func (a ruleModelHasManyActionsTx) Unscoped() *ruleModelHasManyActionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type ruleModelDo struct{ gen.DO }

type IRuleModelDo interface {
	gen.SubQuery
	Debug() IRuleModelDo
	WithContext(ctx context.Context) IRuleModelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRuleModelDo
	WriteDB() IRuleModelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRuleModelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRuleModelDo
	Not(conds ...gen.Condition) IRuleModelDo
	Or(conds ...gen.Condition) IRuleModelDo
	Select(conds ...field.Expr) IRuleModelDo
	Where(conds ...gen.Condition) IRuleModelDo
	Order(conds ...field.Expr) IRuleModelDo
	Distinct(cols ...field.Expr) IRuleModelDo
	Omit(cols ...field.Expr) IRuleModelDo
	Join(table schema.Tabler, on ...field.Expr) IRuleModelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRuleModelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRuleModelDo
	Group(cols ...field.Expr) IRuleModelDo
	Having(conds ...gen.Condition) IRuleModelDo
	Limit(limit int) IRuleModelDo
	Offset(offset int) IRuleModelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRuleModelDo
	Unscoped() IRuleModelDo
	Create(values ...*model.RuleModel) error
	CreateInBatches(values []*model.RuleModel, batchSize int) error
	Save(values ...*model.RuleModel) error
	First() (*model.RuleModel, error)
	Take() (*model.RuleModel, error)
	Last() (*model.RuleModel, error)
	Find() ([]*model.RuleModel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RuleModel, err error)
	FindInBatches(result *[]*model.RuleModel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RuleModel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRuleModelDo
	Assign(attrs ...field.AssignExpr) IRuleModelDo
	Joins(fields ...field.RelationField) IRuleModelDo
	Preload(fields ...field.RelationField) IRuleModelDo
	FirstOrInit() (*model.RuleModel, error)
	FirstOrCreate() (*model.RuleModel, error)
	FindByPage(offset int, limit int) (result []*model.RuleModel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRuleModelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r ruleModelDo) Debug() IRuleModelDo {
	return r.withDO(r.DO.Debug())
}

func (r ruleModelDo) WithContext(ctx context.Context) IRuleModelDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r ruleModelDo) ReadDB() IRuleModelDo {
	return r.Clauses(dbresolver.Read)
}

func (r ruleModelDo) WriteDB() IRuleModelDo {
	return r.Clauses(dbresolver.Write)
}

func (r ruleModelDo) Session(config *gorm.Session) IRuleModelDo {
	return r.withDO(r.DO.Session(config))
}

func (r ruleModelDo) Clauses(conds ...clause.Expression) IRuleModelDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r ruleModelDo) Returning(value interface{}, columns ...string) IRuleModelDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r ruleModelDo) Not(conds ...gen.Condition) IRuleModelDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r ruleModelDo) Or(conds ...gen.Condition) IRuleModelDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r ruleModelDo) Select(conds ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r ruleModelDo) Where(conds ...gen.Condition) IRuleModelDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r ruleModelDo) Order(conds ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r ruleModelDo) Distinct(cols ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r ruleModelDo) Omit(cols ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r ruleModelDo) Join(table schema.Tabler, on ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r ruleModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r ruleModelDo) RightJoin(table schema.Tabler, on ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r ruleModelDo) Group(cols ...field.Expr) IRuleModelDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r ruleModelDo) Having(conds ...gen.Condition) IRuleModelDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r ruleModelDo) Limit(limit int) IRuleModelDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r ruleModelDo) Offset(offset int) IRuleModelDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r ruleModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRuleModelDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r ruleModelDo) Unscoped() IRuleModelDo {
	return r.withDO(r.DO.Unscoped())
}

func (r ruleModelDo) Create(values ...*model.RuleModel) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r ruleModelDo) CreateInBatches(values []*model.RuleModel, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r ruleModelDo) Save(values ...*model.RuleModel) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r ruleModelDo) First() (*model.RuleModel, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleModel), nil
	}
}

func (r ruleModelDo) Take() (*model.RuleModel, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleModel), nil
	}
}

func (r ruleModelDo) Last() (*model.RuleModel, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleModel), nil
	}
}

func (r ruleModelDo) Find() ([]*model.RuleModel, error) {
	result, err := r.DO.Find()
	return result.([]*model.RuleModel), err
}

func (r ruleModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RuleModel, err error) {
	buf := make([]*model.RuleModel, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r ruleModelDo) FindInBatches(result *[]*model.RuleModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r ruleModelDo) Attrs(attrs ...field.AssignExpr) IRuleModelDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r ruleModelDo) Assign(attrs ...field.AssignExpr) IRuleModelDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r ruleModelDo) Joins(fields ...field.RelationField) IRuleModelDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r ruleModelDo) Preload(fields ...field.RelationField) IRuleModelDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r ruleModelDo) FirstOrInit() (*model.RuleModel, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleModel), nil
	}
}

func (r ruleModelDo) FirstOrCreate() (*model.RuleModel, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RuleModel), nil
	}
}

func (r ruleModelDo) FindByPage(offset int, limit int) (result []*model.RuleModel, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r ruleModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r ruleModelDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r ruleModelDo) Delete(models ...*model.RuleModel) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *ruleModelDo) withDO(do gen.Dao) *ruleModelDo {
	r.DO = *do.(*gen.DO)
	return r
}
